# SPDX-FileCopyrightText: Copyright (c) 2025 Orange
# SPDX-License-Identifier: Mozilla Public License 2.0
#
# This software is distributed under the MPL-2.0 license.
# the text of which is available at https://www.mozilla.org/en-US/MPL/2.0/
# or see the "LICENSE" file for more details.

project_name: terraform-resource-templates
version: 2
before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
      # Default: [ 'darwin', 'linux', 'windows' ]
      # Default: [ '386', 'amd64', 'arm64' ]
    #binary: '{{ .ProjectName }}_{{ .Version }}'
    binary: terraform-resource-templates
    ldflags:
      - '-s -w -X github.com/orange-cloudavenue/terraform-resource-templates/main.version={{.Version}}'

archives:
  - format: tar.gz
    format_overrides:
      - format: zip
        goos: 'windows'
    wrap_in_directory: true
    # this name template makes the OS and Arch compatible with the results of `uname`.
    name_template: '{{ .ProjectName }}_v{{ .Version }}_{{ .Os }}_{{ .Arch }}'
    files:
      - README.md

